import type { PointName } from "../types/points.js";

export const POINT_GLYPHS: Record<PointName, string> = {
  sun: "\u2609",
  moon: "\u263D",
  mercury: "\u263F",
  venus: "\u2640",
  mars: "\u2642",
  jupiter: "\u2643",
  saturn: "\u2644",
  uranus: "\u2645",
  neptune: "\u2646",
  pluto: "\u2647",
  northNode: "\u260A",
  southNode: "\u260B",
  chiron: "\u26B7",
  lilith: "\u26B8",
  ascendant: "AC",
  midheaven: "MC",
  vertex: "Vx",
  partOfFortune: "\u2297",
};

export const POINT_LABELS: Record<PointName, string> = {
  sun: "Sun",
  moon: "Moon",
  mercury: "Mercury",
  venus: "Venus",
  mars: "Mars",
  jupiter: "Jupiter",
  saturn: "Saturn",
  uranus: "Uranus",
  neptune: "Neptune",
  pluto: "Pluto",
  northNode: "North Node",
  southNode: "South Node",
  chiron: "Chiron",
  lilith: "Lilith",
  ascendant: "Ascendant",
  midheaven: "Midheaven",
  vertex: "Vertex",
  partOfFortune: "Part of Fortune",
};

/** Relative weight of each point when computing compatibility scores (0-1). */
export const POINT_SIGNIFICANCE_WEIGHT: Record<PointName, number> = {
  sun: 1,
  moon: 1,
  mercury: 0.6,
  venus: 0.9,
  mars: 0.9,
  jupiter: 0.5,
  saturn: 0.7,
  uranus: 0.3,
  neptune: 0.3,
  pluto: 0.4,
  northNode: 0.4,
  southNode: 0.2,
  chiron: 0.3,
  lilith: 0.3,
  ascendant: 0.8,
  midheaven: 0.5,
  vertex: 0.3,
  partOfFortune: 0.2,
};
